---
title: "che"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{che}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Working example of using Convex Hull Ensembles and range bagging with the `che` package
## Matt Hill 2019

```{r setup}
library(che)
library (raster)
library (maptools)
library (rgeos)
```

## this data is the in the `che` package - will implement neater soon....
```{r}
load("../data/insect_dist.Rdata")
```

## Bioclim data
```{r}
bioclimall <- raster::getData('worldclim', var='bio', res=2.5)
```

## Native range for this species is South Africad
```{r}
e <- extent (10, 40, -35, -15)
SAfrica <- crop (bioclimall, e)
#convert to a stack
SAfrica <- stack(unstack(SAfrica))
```

```{r}
dist <- insect_dist[insect_dist$Species =="h_destructor" & insect_dist$Range == "Native",]

sp_df <- cbind(as.data.frame(dist[,c("Longitude", "Latitude")]),raster::extract(SAfrica, as.data.frame(dist[,c("Longitude", "Latitude")])))
plot (SAfrica[[1]])
points(as.data.frame(dist[,c("Longitude", "Latitude")]), pch=20)
```

